title: "Keycuts"
description: "Keyboard shortcuts on steroids !"
avatar: ""
baseurl: ""

social:
  email: 
  facebook:  
  github:  
  instagram:  
  linkedin:  
  pinterest:  
  skype:  
  twitter:  
  youtube:  
  rss: # just type anything here for a working RSS icon
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  googleplus: # anything in your profile username that comes after plus.google.com/
